name: Development

on:
    push:
        branches:
            - main

jobs:
    release:
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                platform: [ubuntu-20.04]
        runs-on: ${{ matrix.platform }}

        steps:
            -   name: Checkout Repository
                uses: actions/checkout@v4
            -   name: Setup NodeJS
                uses: actions/setup-node@v4
                with:
                    node-version: 18
            -   name: Install Rust
                uses: dtolnay/rust-toolchain@stable
            -   name: Install System Dependencies (Ubuntu only)
                if: matrix.platform == 'ubuntu-20.04'
                run: |
                    sudo apt update
                    sudo apt install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev
            -   name: Install Frontend Dependencies
                run: npm install
            -   name: Build Application
                run: npm run build
            -   name: Publish Application
                uses: actions/upload-artifact@v3
                with:
                    name: tauri-experiments_linux-version
                    path: ./src-tauri/target/release/tauri-experiments
