name: Release

on:
    push:
        tags:
            - "v*"

jobs:
    release:
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                platform: [ubuntu-22.04]
        runs-on: ${{ matrix.platform }}

        steps:
            - name: checkout repository
              uses: actions/checkout@v4.1.1
            - name: install system dependencies (ubuntu only)
              if: matrix.platform == "ubuntu-22.04"
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libayatana-appindicator3-dev librsvg2-dev
            - name: install nodejs
              uses: actions/setup-node@v4.0.2
              with:
                  node-version: "21"
                  # cache: 'npm'
            - name: install rust
              uses: dtolnay/rust-toolchain@stable
            - name: install project dependencies
              run: npm install
            - name: build the app
              uses: tauri-apps/tauri-action@v0.5.1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tagName: ${{ github.ref_name }}
                  releaseName: "App Name v__VERSION__"
                  releaseBody: "See the assets to download and install this version."
                  releaseDraft: true
                  prerelease: false
